### ISSUE TITLE
What would this resolve?

### ISSUE THREAD

**Issue by ghyujkilop** [ixanza/GDOPatcher#1]
If I only use Guard dialogue overhaul, how would using this patcher to pull forward spike keywords do anything?

**Comment by ixanza** [comment]
this doesn't pull forward anything. Based on the weapon or armor material keywords it adds SPIKE keywords

**Comment by ghyujkilop** [comment]
So, using just GDO, there's nothing extra I could benefit from using this right? I'm just struggling to understand the benefit is all.
